apiVersion: v1
kind: Pod
metadata:
  name: init-container
spec:
  initContainers:
  - name: busybox
    image: busybox
    command: ["/bin/bash"]
    args: ["-c", "echo 'This is busybox init-container'; sleep 20"]
  containers:
  - name: ip-app
    image: shankaru/ip_app:v1
    ports:
    - containerPort: 80
