apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-configmap-volume
spec:
  containers:
  - name: ip-app
    image: shankaru/ip_app:v1
    ports:
    - containerPort: 80
    volumeMount:
    - name: secret-vol
      mountPath: '/app/volume/secret'
    - name: configmap-vol
      mountPath: '/app/volume/configmap'

  volumes:
  - name: secret-vol
    secret:
      secretName: my-secret-vol
  - name: configmap-vol
    configMap:
      secretName: my-cm-vol
