apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
        - matchExpressions:
        - key: environment
          operator: In
          values:
          - qa
          - stagging
  containers:
  - name: ip-app
    image: shankaru/ip_app:v1
    ports:
    - containerPort: 80
