apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-sa-cluster-role-binding
  namesapce: default
subjects:
- kind: ServiceAccount
  name: my-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: my-sa-cluster-role
