apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-sa-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes", "namespace"]
  verbs: ["get", "list", "watch"]
