apiVersion: v1
kind: Service
metadata:
  name: ci-svc-1
spec:
  clusterIP: None
  selector:
    app: ip-app-statefullset
  ports:
  - name: http
    port: 30002
    targetPort: 8080


---
apiVersion: apps/v1
kind: StatefullSet
metadata:
  name: ip-app-statefullset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ip-app-statefullset
  template:
    metadata:
      labels:
        app: ip-app-statefullset
    spec:
      containers:
      - name: ip-app
        image: shankaru/ip_app:v1
        ports:
        - containerPort: 8080
