apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress-all
spec:
  podSelector:
    matchLabels:
      app: ip-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.110.180.218/16
      podSelector:
        matchLabels:
          app: frontend
    ports:
    - protocol: TCP
      port: 30000
