apiVersion: v1
kind: Pod
metadata:
  name: ip-app-resource-quota
spec:
  containers:
  - name: ip-app
    image: shankaru/ip_app:v1
    ports:
    - containerPort: 80
    resource:
      requests:
        meomry: 100Mi
      limits:
        memory: 150Mi

